[project]
name = "demo-cloud-composer-earth-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow==2.10.5",
    "apache-airflow-providers-google>=17.1.0",
    "earthengine-api>=1.6.4",
]
